prompts:
  # - file://prompts1.txt
  # - file://prompts2.txt
  - id: file://prompts1.txt
    label: a
  - id: file://prompts2.txt
    label: b

providers:
  - id: openai:gpt-4o
    label: 4o
    prompts:
      - a
    #  - b
  - id: openai:gpt-3.5-turbo
    label: '3.5'
    prompts:
      #  - a
      - b

tests:
  - vars:
      topic: large language models
    assert:
      - type: select-best
        value: choose the tweet most likely to lead to AGI

  - vars:
      topic: nyc
    assert:
      - type: select-best
        value: choose the tweet that contains the most silly facts
