prompts:
  - prompts.txt

extensions:
  - python:customPlugin.py

providers: [openai:gpt-4o]

tests:
  - vars:
      body: Hello world
      setup: touch setup1
      teardown: touch teardown1
  - vars:
      body: I'm hungry
      setup: touch setup2
      teardown: touch teardown2
