prompts:
  - file://prompts1.txt
  - file://prompts2.txt

providers:
  - id: openai:gpt-4o
    label: 4o
  - id: openai:gpt-3.5-turbo
    label: '3.5'

tests:
  - vars:
      topic: bananas
    assert:
      - type: select-best
        value: choose the funniest tweet

  - vars:
      topic: nyc
    assert:
      - type: select-best
        value: choose the tweet that contains the most facts
