providers:
  - id: anthropic:messages:claude-3-5-sonnet-20240620
    config:
      temperature: 0.3
      max_tokens: 1024
  - id: openai:gpt-4o
    config:
      temperature: 0.3
      max_tokens: 1024

prompts:
  - file://prompt.yaml

tests:
  - vars:
      riddle: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?'
    assert:
      - type: icontains
        value: echo
  - vars:
      riddle: "You see a boat filled with people. It has not sunk, but when you look again you don't see a single person on the boat. Why?"
    assert:
      - type: llm-rubric
        value: explains that the people are below deck or they are all in a relationship
  - vars:
      riddle: 'The more of this there is, the less you see. What is it?'
    assert:
      - type: icontains
        value: darkness

defaultTest:
  assert:
    - type: cost
      threshold: 0.01
    - type: latency
      threshold: 3000
    - type: javascript
      value: 'output.length <= 100 ? 1 : output.length > 1000 ? 0 : 1 - (output.length - 100) / 900'

outputPath: ./results.json