description: Extension Hook Example

prompts:
  - 'Rephrase this in French: {{body}}'
  - 'Rephrase this like a pirate: {{body}}'

providers:
  - openai:gpt-4o-mini

extensions:
  - file://hooks.js:extensionHook
  # - python:hooks.py

tests:
  - vars:
      riddle: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?'
    assert:
      - type: contains
        value: echo
      - type: llm-rubric
        value: Do not apologize
  - vars:
      riddle: 'You see a boat filled with people. It has not sunk, but when you look again you don’t see a single person on the boat. Why?'
    assert:
      - type: llm-rubric
        value: explains that the people are below deck
  - vars:
      riddle: 'The more of this there is, the less you see. What is it?'
    assert:
      - type: contains
        value: darkness
