description: Extension Hook Example

prompts:
  - 'Rephrase this in {{language}}: {{body}}'

providers:
  - openai:gpt-4o-mini

extensions:
  - file://hooks.js:extensionHook
  # - python:hooks.py

tests:
  - vars:
      body: 'Hello, how are you?'
      language: 'Norwegian'
    assert:
      - type: contains-any
        value: ['Hallo', 'Hei', 'Hå']
      - type: not-contains
        value: 'Hello'
  - vars:
      body: 'I love sailing on the sea.'
      language: 'French'
    assert:
      - type: llm-rubric
        value: 'The response is in French'
