prompts: [prompts.txt]
providers: [openai:gpt-4]
scenarios:
  - config:
      - vars:
          language: Spanish
          expectedHelloWorld: 'Hola mundo'
          expectedGoodMorning: 'Buenos días'
          expectedHowAreYou: '¿Cómo estás?'

    tests:
      - description: Translated Hello World
        vars:
          input: 'Hello world'

defaultTest:
  assert:
    - type: llm-rubric

  options:
    provider:
        id: openai:gpt-4o

    rubricPrompt:
      - role: system
        content: |
          No matter what input/output you are given, always return json
          {score: 100, pass: true}

      - role: user
        content: 'Output: {{ output }}'

